package Chapter02.Exercises;

public class Exercise11 {
    public static void main(String[] args) {

    }
}
/*
Modify your code from the previous exercise so that it could easily be modified to display a different range of numbers
(instead of 1234567890) and a different number of repetitions of those numbers (instead of 60 total characters),
with the vertical bars still matching up correctly. Use class constants instead of “magic numbers.”
Here are some example outputs that could be generated by changing your constants:

    |    |    |    |    |    |    |    |    |    |
12340123401234012340123401234012340123401234012340
       |       |       |       |       |       |       |
12345670123456701234567012345670123456701234567012345670
 */