package Chapter02.Exercises;

public class Exercise11 {
    // Values that can be changed (Will look weird unless TOTAL_WIDTH % SECTION_WIDTH = 0).
    public static final int TOTAL_WIDTH = 36;
    public static final int SECTION_WIDTH = 6;
    // Formula to make method "bottom" work real good
    public static final int SECTIONS = TOTAL_WIDTH / SECTION_WIDTH;

    public static void main(String[] args) {
        cleanOutput();
    }

    // Makes output a little more clean.
    public static void cleanOutput() {
        top();
        bottom();
    }

    // 6 loops of a 10-character wide string w/ a '|' at the end
    public static void top() {
        for (int i = 1; i <= SECTIONS; i++) {
            for (int j = 1; j < SECTION_WIDTH; j++) {
                System.out.print(" ");
            }
            System.out.print("|");
        }
        System.out.println();
    }

    //
    public static void bottom() {
        for (int i = 1; i <= TOTAL_WIDTH; i++) {
            final int remainder = i % SECTION_WIDTH;

            System.out.print(remainder);
        }
        System.out.println();
    }
}
/*
Modify your code from the previous exercise so that it could easily be modified to display a different range of numbers
(instead of 1234567890) and a different number of repetitions of those numbers (instead of 60 total characters),
with the vertical bars still matching up correctly. Use class constants instead of “magic numbers.”
Here are some example outputs that could be generated by changing your constants:

    |    |    |    |    |    |    |    |    |    |
12340123401234012340123401234012340123401234012340
       |       |       |       |       |       |       |
12345670123456701234567012345670123456701234567012345670
 */